export { default as authService } from './authService'
export { default as appointmentService } from './appointmentService'
export { default as doctorService } from './doctorService'
export { default as prescriptionService } from './prescriptionService'
export { default as api } from './api'
export type { CreateAppointmentData, UpdateAppointmentStatusData } from './appointmentService'
export type { DoctorSearchParams, UpdateDoctorProfileData, UpdateScheduleData } from './doctorService'
export type { MedicineItem, CreatePrescriptionData, UpdatePrescriptionData } from './prescriptionService'